#include "qube_servo2_gui/ui/pages/recording_dialog.hpp"
#include <QCheckBox>
#include <QComboBox>
#include <QDir>
#include <QDoubleSpinBox>
#include <QFileDialog>
#include <QFormLayout>
#include <QFrame>
#include <QGridLayout>
#include <QHBoxLayout>
#include <QLabel>
#include <QLineEdit>
#include <QPushButton>
#include <QSpinBox>
#include <QStandardPaths>
#include <QTextEdit>
#include <QVBoxLayout>

namespace qube_servo2::gui::ui::pages {
namespace {
QDoubleSpinBox* ds(QWidget* p,double lo,double hi,double v,int dec,double step){auto* s=new QDoubleSpinBox(p);s->setRange(lo,hi);s->setValue(v);s->setDecimals(dec);s->setSingleStep(step);s->setKeyboardTracking(false);return s;}
}
RecordingDialog::RecordingDialog(QWidget* parent):QDialog(parent){
 setWindowTitle("QUBE-Servo 2 / Data Acquisition"); setModal(false); setMinimumSize(780,650); resize(860,700);
 auto* root=new QVBoxLayout(this); root->setContentsMargins(14,14,14,14); root->setSpacing(10); auto* title=new QLabel("EXPERIMENT RECORDING",this);title->setObjectName("title");root->addWidget(title);
 auto* panel=new QFrame(this);panel->setObjectName("panel");auto* pv=new QVBoxLayout(panel);auto* form=new QFormLayout(); form->setLabelAlignment(Qt::AlignRight|Qt::AlignVCenter);
 auto* dr=new QHBoxLayout();directory_edit_=new QLineEdit(panel);directory_edit_->setText(QDir(QStandardPaths::writableLocation(QStandardPaths::DocumentsLocation)).filePath("qube_servo2_data"));auto* browse=new QPushButton("Browse",panel);browse->setObjectName("secondary");connect(browse,&QPushButton::clicked,this,&RecordingDialog::browseDirectory_);dr->addWidget(directory_edit_,1);dr->addWidget(browse);form->addRow("Output directory",dr);prefix_edit_=new QLineEdit("qube_run",panel);form->addRow("File prefix",prefix_edit_);notes_edit_=new QTextEdit(panel);notes_edit_->setMaximumHeight(70);notes_edit_->setPlaceholderText("Experiment objective, controller, gains, conditions…");form->addRow("Notes",notes_edit_);metadata_check_=new QCheckBox("Write companion YAML metadata file",panel);metadata_check_->setChecked(true);form->addRow("",metadata_check_);pv->addLayout(form);
 auto* cp=new QFrame(panel);cp->setObjectName("subPanel");auto* cv=new QVBoxLayout(cp);auto* ct=new QLabel("SMART CAPTURE",cp);ct->setObjectName("panelTitle");cv->addWidget(ct);auto* cg=new QGridLayout();capture_mode_=new QComboBox(cp);capture_mode_->addItems({"Manual / continuous","Time window","N periods","Peak count"});sample_interval_ms_=new QSpinBox(cp);sample_interval_ms_->setRange(0,10000);sample_interval_ms_->setSuffix(" ms");cg->addWidget(new QLabel("Capture mode",cp),0,0);cg->addWidget(capture_mode_,0,1);cg->addWidget(new QLabel("Save interval",cp),0,2);cg->addWidget(sample_interval_ms_,0,3);waveform_info_=new QLabel("Waveform: --",cp);waveform_info_->setObjectName("subtitle");cg->addWidget(waveform_info_,1,0,1,4);cv->addLayout(cg);
 timing_fields_=new QWidget(cp);auto* tg=new QGridLayout(timing_fields_);tg->setContentsMargins(0,0,0,0);start_delay_s_=ds(timing_fields_,0,3600,0,3,.1);duration_s_=ds(timing_fields_,.001,86400,10,3,.5);period_count_=new QSpinBox(timing_fields_);period_count_->setRange(1,100000);period_count_->setValue(10);duration_field_=duration_s_;periods_field_=period_count_;tg->addWidget(new QLabel("Start delay [s]",timing_fields_),0,0);tg->addWidget(start_delay_s_,0,1);tg->addWidget(new QLabel("Duration [s]",timing_fields_),0,2);tg->addWidget(duration_s_,0,3);tg->addWidget(new QLabel("Periods",timing_fields_),1,0);tg->addWidget(period_count_,1,1);cv->addWidget(timing_fields_);
 peak_fields_=new QWidget(cp);auto* pg=new QGridLayout(peak_fields_);pg->setContentsMargins(0,0,0,0);peak_signal_=new QComboBox(peak_fields_);peak_signal_->addItems({"Velocity","Current","Torque","Applied voltage","Position","Electrical power","Mechanical power"});peak_threshold_=ds(peak_fields_,0,1e9,1,6,.1);peak_separation_s_=ds(peak_fields_,0,3600,.1,3,.05);peak_target_count_=new QSpinBox(peak_fields_);peak_target_count_->setRange(1,100000);peak_target_count_->setValue(5);peak_absolute_=new QCheckBox("Detect absolute magnitude peaks",peak_fields_);peak_absolute_->setChecked(true);pg->addWidget(new QLabel("Peak signal",peak_fields_),0,0);pg->addWidget(peak_signal_,0,1);pg->addWidget(new QLabel("Threshold",peak_fields_),0,2);pg->addWidget(peak_threshold_,0,3);pg->addWidget(new QLabel("Min separation [s]",peak_fields_),1,0);pg->addWidget(peak_separation_s_,1,1);pg->addWidget(new QLabel("Stop after",peak_fields_),1,2);pg->addWidget(peak_target_count_,1,3);pg->addWidget(peak_absolute_,2,0,1,4);cv->addWidget(peak_fields_);pv->addWidget(cp);
 auto* st=new QFrame(panel);st->setObjectName("subPanel");auto* sg=new QGridLayout(st);state_label_=new QLabel("IDLE",st);state_label_->setObjectName("metricValue");samples_label_=new QLabel("0",st);samples_label_->setObjectName("metricValue");peaks_label_=new QLabel("0",st);peaks_label_->setObjectName("metricValue");duration_label_=new QLabel("0.000 s",st);duration_label_->setObjectName("metricValue");file_label_=new QLabel("--",st);file_label_->setWordWrap(true);file_label_->setTextInteractionFlags(Qt::TextSelectableByMouse);error_label_=new QLabel("",st);error_label_->setObjectName("errorText");error_label_->setWordWrap(true);sg->addWidget(new QLabel("STATE",st),0,0);sg->addWidget(state_label_,0,1);sg->addWidget(new QLabel("SAMPLES",st),0,2);sg->addWidget(samples_label_,0,3);sg->addWidget(new QLabel("PEAKS",st),0,4);sg->addWidget(peaks_label_,0,5);sg->addWidget(new QLabel("ELAPSED",st),0,6);sg->addWidget(duration_label_,0,7);sg->addWidget(new QLabel("FILE",st),1,0);sg->addWidget(file_label_,1,1,1,7);sg->addWidget(error_label_,2,0,1,8);pv->addWidget(st);
 auto* br=new QHBoxLayout();start_btn_=new QPushButton("Start recording",panel);stop_btn_=new QPushButton("Stop recording",panel);stop_btn_->setObjectName("secondary");stop_btn_->setEnabled(false);auto* close=new QPushButton("Close",panel);close->setObjectName("secondary");connect(start_btn_,&QPushButton::clicked,this,&RecordingDialog::startRecordingRequested);connect(stop_btn_,&QPushButton::clicked,this,&RecordingDialog::stopRecordingRequested);connect(close,&QPushButton::clicked,this,&QDialog::hide);br->addWidget(start_btn_);br->addWidget(stop_btn_);br->addStretch(1);br->addWidget(close);pv->addLayout(br);root->addWidget(panel,1);connect(capture_mode_,&QComboBox::currentIndexChanged,this,&RecordingDialog::updateCaptureModeUi_);updateCaptureModeUi_();
}
QString RecordingDialog::directory()const{return directory_edit_->text().trimmed();} QString RecordingDialog::prefix()const{return prefix_edit_->text().trimmed();} QString RecordingDialog::notes()const{return notes_edit_->toPlainText();} bool RecordingDialog::writeMetadata()const noexcept{return metadata_check_->isChecked();}
models::RecordingConfig RecordingDialog::recordingConfig()const{models::RecordingConfig c;c.mode=static_cast<models::RecordingMode>(capture_mode_->currentIndex());c.sample_interval_ms=sample_interval_ms_->value();c.start_delay_s=start_delay_s_->value();c.duration_s=duration_s_->value();c.period_count=period_count_->value();c.peak_signal=static_cast<models::PeakSignal>(peak_signal_->currentIndex());c.peak_threshold=peak_threshold_->value();c.min_peak_distance_s=peak_separation_s_->value();c.peak_target_count=peak_target_count_->value();c.absolute_peaks=peak_absolute_->isChecked();return c;}
void RecordingDialog::setRecordingState(bool a){if(!a)state_label_->setText("IDLE");start_btn_->setEnabled(!a);stop_btn_->setEnabled(a);capture_mode_->setEnabled(!a);} void RecordingDialog::setStats(qint64 s,double sec,const QString& fpath){samples_label_->setText(QString::number(s));duration_label_->setText(QString::number(sec,'f',3)+" s");file_label_->setText(fpath.isEmpty()?"--":fpath);} void RecordingDialog::setPeakCount(int p){peaks_label_->setText(QString::number(p));} void RecordingDialog::setCaptureStatus(const QString& s){state_label_->setText(s);} void RecordingDialog::setWaveformInfo(const models::WaveformConfig& w){waveform_info_->setText(QString("Waveform: %1 · f=%2 Hz · duration=%3 s").arg(w.name()).arg(w.frequency_hz,0,'g',6).arg(w.duration_s,0,'g',6));} void RecordingDialog::showError(const QString& m){error_label_->setText(m);} void RecordingDialog::browseDirectory_(){const QString x=QFileDialog::getExistingDirectory(this,"Select data directory",directory());if(!x.isEmpty())directory_edit_->setText(x);} void RecordingDialog::updateCaptureModeUi_(){const auto m=static_cast<models::RecordingMode>(capture_mode_->currentIndex());timing_fields_->setVisible(m==models::RecordingMode::TimeWindow||m==models::RecordingMode::PeriodCount);duration_s_->setVisible(m==models::RecordingMode::TimeWindow);period_count_->setVisible(m==models::RecordingMode::PeriodCount);peak_fields_->setVisible(m==models::RecordingMode::PeakCount);}
}
