controller_manager:
  ros__parameters:
    update_rate: 1000

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    motor_voltage_controller:
      type: qube_servo2_controllers/QubeVoltageController

motor_voltage_controller:
  ros__parameters:
    joint_name: motor_hub_link_joint
    interface_name: voltage
    reference_topic: ~/reference
