qube_servo2:
  ros__parameters:
    motor:
      resistance: 8.4 # Ohm
      inductance: 1.16e-3 # H
      torque_constant: 0.042 # N*m/A
      back_emf_constant: 0.042 # V/(rad/s)
      voltage_limit: 10.0 # V
      peak_current_limit: 2.0 # A
      viscous_friction: 0.001 # N*m/(rad/s)
      coulomb_friction: 0.0 # N*m
      friction_smoothing: 0.1 # rad/s
